language: python
sudo: false
env:
   global:
     - OFFICIAL_REPO="slaclab/pswalker"
     - secure: "hK8k7lISV1MMkoEKqXeyQUGH0mcyBSJWwHMjMgdOjd0H7csQA6qq6RZoTxRQkzwlbKTjfE7Vn0HMuYHlrPnkXJZ3VKuYjIukrDnDvtU2wgDiNadqb/dASODBctynacBg8MHoCFhnUcgWrw1MJ4eHBctmb2yQDqwWpFdeBZ+WXvYsIBNAONiMfj0Ka5cUeCnmKSER5J7tP2UwFD5ihFl45ZPDb0Smj1E0NAXutuVos934R4+AWqPXAhNVfI6Y7FzCeHup1QM9hB9xvgF3OdSLvb4vlrLje+Cp8SVO8j41FVXZEpsMUlc+vKShRNAjhKL6IbA6DwqwObo54s9mxhrRGntONZdCTPAMFBM86YtEyMS9fpvshP1wISj58fZPscjg1ozp2npiLZtZvVjuaeJ3/YtUfEiH4hRmFm8yWYHt0g+ONx1CfYwAySAkWdmV+MAywmsOMPYOkTD4FLsNNDZDA4dMiqKNE9dqjtd1hXVAM6bGNbSKU5z3fSx1LNhfbNyzPhhxbAN1BA/3Lh6bJN5UXvKcyuu8JOIsn0qKZ90HsqGgfmfxR1keBEgyjMO8xyErIH+6TAxfyIcFWxLdDFxxQMyEcBDLllDAUKirvkHUdYpZRsN7o1hkYmBHBA5W+Bvyvr726Y60mc8IN+H1YLpQhwll/6bs5KOwDC1ZflTAzqo="

matrix:
  include:
     - python: 3.5
     - python: 3.6
       env: BUILD_DOCS=1

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  #Grab all dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION coverage pip wheel ophyd==1.0.0 bluesky==1.0.0 event-model=1.3.0 pytest pcds-devices=0.2.0 lightpath=0.2.1 psbeam=0.0.3 -c conda-forge -c skywalker-tag -c gsecars -c lightsource2-tag -c pydm-dev -c paulscherrerinstitute
  #Launch Conda environment
  - source activate test-environment
  #Install pedl
  - pip install codecov
  - pip install -r requirements.txt
  #Install
  - python setup.py install

script:
  - coverage run run_tests.py
  - coverage report -m
  - set -e
  #Build docs
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY" && $BUILD_DOCS ]]; then
      pip install -r docs-requirements.txt
      # Install doctr from a custom branch until
      # https://github.com/drdoctr/doctr/pull/190 is merged.
      pip uninstall -y doctr
      pip install git+https://github.com/danielballan/doctr@other-master
      pushd docs
      make html
      popd
      #Publish docs.
      doctr deploy --deploy-repo lcls-pcds/skywalker-docs --deploy-branch-name master pswalker
    fi

after_success:
  - codecov
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' && $CONDA_UPLOAD_TOKEN_TAG != '' ]]; then
      conda build . -c conda-forge -c skywalker-tag -c gsecars -c lightsource2-tag -c pydm-dev -c paulscherrerinstitute --token $CONDA_UPLOAD_TOKEN_TAG --python $TRAVIS_PYTHON_VERSION
    fi
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG == '' && $CONDA_UPLOAD_TOKEN_DEV != '' ]]; then
      conda build . -c conda-forge -c skywalker-tag -c gsecars -c lightsource2-tag -c pydm-dev -c paulscherrerinstitute --token $CONDA_UPLOAD_TOKEN_DEV --python $TRAVIS_PYTHON_VERSION
    fi
